apiVersion: openchoreo.dev/v1alpha1
kind: WorkflowRun
metadata:
  name: github-create-repo-run-01
spec:
  workflow:
    name: github-create-repo
    parameters:
      github:
        org: "lakshanss"
        repoName: "test-repo-openchoreo-wf1"
      repo:
        description: "A new repository created via the self-service workflow"
        private: true
        autoInit: true
